language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install pandas pytest flake8
  - python setup.py install

script:
    - python -m flake8 shelter/data.py --show-source
    - python -m pytest tests/
